FROM fedora:41

COPY . /

## Original
## RUN dnf update -y
##
## RUN dnf install ncurses util-linux util-linux-user passwd nano vim git wget @core sqlite pinentry cracklib-dicts -y

RUN dnf update -y && \
    dnf install -y ncurses util-linux util-linux-user passwd nano vim git wget @core sqlite pinentry cracklib-dicts gettext-envsubst podman python3-pip tree glibc-all-langpacks && \
    dnf clean all

